[build]
builder = "nixpacks"
buildCommand = "npm install --prefix MSA && npm run build --prefix MSA"

[deploy]
startCommand = "node MSA/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
